### ISSUE TITLE
Use <div> instead of non-valid custom element names (e.g. <icon>)

### ISSUE THREAD

**Issue by ebidel** [googlearchive/core-field#1]
For example `<icon>`:
https://github.com/Polymer/core-field/blob/master/demo.html#L37

I've seen a lot of people confused about needing "-" in element names. We're not setting a good example when demos use non valid names. `<div>` is just as convenient :)

**Comment by sjmiles** [comment]
I can let this go, but for the record I don't agree with you in principle. IMO this code was much better as `<icon>` than `<div class="icon">`. I understand about the confusion, but dumbing it down is not necessarily doing anybody any favors.
